#!/bin/sh

#A global pipeline fo 17th c. documents: pdf -> ocr -> tokenization -> lemmatization -> POS-tagging

#Requirements
#============
#torch==1.3.1
#rchvision==0.4.2

#To do
#=====
#Create two virtual environments:
#- ~/venc/kraken/ --> kraken 
#- ~/venv/pie/ --> pie-extended

#Download these libraries:
#- pdftoppm --> used to split a pdf into png images (unix system: sudo apt-get poppler-utils)
#- kraken --> used to process the ocr (pip3 install kraken)
#- pie-extended --> used to tokenizer, lemmatize and POS-tag OCR results (pip3 install pie-extended)

#Models used in this pipeline
#============================
#- OCR : Simon Gabay, Thibault Clérice, Christian Reul. OCR17: Ground Truth and Models for 17th c. French Prints (and hopefully more). 2020. ⟨hal-02577236⟩
#- Lemmatizer : (Paper not accepted for now)  https://github.com/e-ditiones/LEM17/releases/tag/v0.1
#- Tokenizer, POS-tagger and Morphogical Analyser : "fr" model downloaded by pie-extended module as follow: pip-extended download fr

#Please email me if you have something to tell about this work at jean-baptiste.tanguy@sorbonne-universite.fr.

# 1. Preprocessings
echo "1. Spliting PDF files into PNG images..."
for file in `ls ./pdf/*.pdf`; do echo $file;pdftoppm -png $file $file; done
echo "Done."

echo "2. Moving the images into ./png/..."
mkdir png
for file in pdf/*.png; do mv $file ./png/; done
echo "Done."

echo "3. Deleting \"digital-born\" images (ex.: generated by Google Books)..."
for file in `ls ./png/*.png`; do python3 remove_generated_images.py $file; done
echo "Done."

# 2. OCR: binarization, segmentation, ocr
echo "4. Kraken virtual environment activation..."
. ~/venv/kraken/bin/activate
echo "Done."

echo "5. Binarization..."
kraken -I "./png/*.png" -o _bin.png binarize
echo "Done."

echo "6. Segmentation and OCR..."
FILE=models/kraken_CORPUS17_SimonGabay.mlmodel
if test -f "$FILE"; then # if the model does exist we use it
    echo "$FILE exists."
else # otherwise we download it
    mkdir models
    #wget https://github.com/e-ditiones/OCR17/raw/master/Models/Kraken.mlmodel -O $FILE 
    wget https://zenodo.org/record/3826894/files/OCR17.zip?download=1 -O $FILE
    fi
kraken -I "./png/*_bin.png" -o .txt segment ocr -m ./models/kraken_CORPUS17_SimonGabay.mlmodel
echo "Done."

echo "7. Moving text files into ./txt/..."
mkdir txt
for file in png/*.txt; do mv $file ./txt/; done
echo "Done."

echo "8. Pie virtual environment activation..."
. ~/venv/pie/bin/activate
echo "Done."

echo "9. Morphosyntactical analysis (pie-extended)..."
for file in `ls ./txt/*.txt`; do pie-extended tag fr $file; done
echo "Done."

echo "10. Moving pie results into ./pie/..."
mkdir pie
for file in `ls ./txt/*-pie.txt`; do mv $file ./pie; done
echo "Done."